@namespace("net.explorviz.avro")
protocol AdapterEventProtocol {
	
	enum EventType {
	    CREATED,
	    DELETED,
	    ACCESS_GRANTED,
	    ACCESS_REVOKED,
	    CLONED
	}
	
	record LandscapeToken {
		string value;
		string ownerId;
		string secret;
		long created;
		string alias;
	}
	
	record TokenEvent {
		EventType type;
		LandscapeToken token;
		string clonedToken;
	}

	record Span {
		string landscapeToken;
		string traceId;
		string spanId;
		string parentSpanId;
		long startTimeEpochMilli;
		long endTimeEpochMilli;
		string kind;
		string namespace;
		string functionName;
		string appName;
		union { null, string } gitCommitChecksum;
		union { null, string } hostname;
		union { null, string } hostIpAddress;
		union { null, string } appInstanceId;
		union { null, string } appLanguage;
		
		// Optional Kubernetes attributes
		union { null, string } k8sPodName;
		union { null, string } k8sNodeName;
		union { null, string } k8sNamespace;
		union { null, string } k8sDeploymentName;
	}
}
