name: Build and Deploy Quarkus Native Image
description: Build and deploy Quarkus native image to DockerHub
inputs:
  platforms:
    description: Architectures for image, e.g. linux/amd64,linux/arm64/v8
    required: true
  docker-username:
    description: User name to log into registry
    required: true
  docker-password:
    description: Password to log into registry
    required: true
  image-name:
    description: Docker image name
    required: true
  image-tag:
    description: Docker image tag
    required: true
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Set up graalvm
      uses: actions/setup-java@v4
      with:
        distribution: "graalvm"
        java-version: "21"
    - name: Build Quarkus Native Image
      shell: sh
      run: |
        ./gradlew clean assemble \
          -Dquarkus.package.type=native \
          -Dquarkus.container-image.push=true \
          -Dquarkus.jib.platforms=${{ inputs.platforms }} \
          -Dquarkus.container-image.name=${{ inputs.image-name }} \
          -Dquarkus.container-image.tag=${{ inputs.image-tag }} \
          -Dquarkus.native.additional-build-args="--initialize-at-run-time=org.apache.kafka.common.security.authenticator.SaslClientAuthenticator\,org.apache.kafka.common.security.oauthbearer.internals.expiring.ExpiringCredentialRefreshingLogin" \
          -Dquarkus.container-image.username=${{ inputs.docker-username }} \
          -Dquarkus.container-image.password=${{ inputs.docker-password }}
