// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: dump/v1/dump.proto

package io.opencensus.proto.dump;

/**
 * <pre>
 * Used to dump spans for later store&amp;process
 * </pre>
 *
 * Protobuf type {@code opencensus.proto.dump.v1.DumpSpans}
 */
public final class DumpSpans extends com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:opencensus.proto.dump.v1.DumpSpans)
    DumpSpansOrBuilder {
  private static final long serialVersionUID = 0L;

  // Use DumpSpans.newBuilder() to construct.
  private DumpSpans(final com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private DumpSpans() {
    this.spans_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private DumpSpans(final com.google.protobuf.CodedInputStream input,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    final com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        final int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              this.spans_ = new java.util.ArrayList<>();
              mutable_bitField0_ |= 0x00000001;
            }
            this.spans_.add(
                input.readMessage(io.opencensus.proto.trace.v1.Span.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!this.parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (final com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (final java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      if ((mutable_bitField0_ & 0x00000001) != 0) {
        this.spans_ = java.util.Collections.unmodifiableList(this.spans_);
      }
      this.unknownFields = unknownFields.build();
      this.makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return DumpProto.internal_static_opencensus_proto_dump_v1_DumpSpans_descriptor;
  }

  @Override
  protected FieldAccessorTable internalGetFieldAccessorTable() {
    return DumpProto.internal_static_opencensus_proto_dump_v1_DumpSpans_fieldAccessorTable
        .ensureFieldAccessorsInitialized(DumpSpans.class, Builder.class);
  }

  public static final int SPANS_FIELD_NUMBER = 1;
  private java.util.List<io.opencensus.proto.trace.v1.Span> spans_;

  /**
   * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
   */
  @Override
  public java.util.List<io.opencensus.proto.trace.v1.Span> getSpansList() {
    return this.spans_;
  }

  /**
   * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
   */
  @Override
  public java.util.List<? extends io.opencensus.proto.trace.v1.SpanOrBuilder> getSpansOrBuilderList() {
    return this.spans_;
  }

  /**
   * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
   */
  @Override
  public int getSpansCount() {
    return this.spans_.size();
  }

  /**
   * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
   */
  @Override
  public io.opencensus.proto.trace.v1.Span getSpans(final int index) {
    return this.spans_.get(index);
  }

  /**
   * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
   */
  @Override
  public io.opencensus.proto.trace.v1.SpanOrBuilder getSpansOrBuilder(final int index) {
    return this.spans_.get(index);
  }

  private byte memoizedIsInitialized = -1;

  @Override
  public final boolean isInitialized() {
    final byte isInitialized = this.memoizedIsInitialized;
    if (isInitialized == 1) {
      return true;
    }
    if (isInitialized == 0) {
      return false;
    }

    this.memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(final com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
    for (int i = 0; i < this.spans_.size(); i++) {
      output.writeMessage(1, this.spans_.get(i));
    }
    this.unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = this.memoizedSize;
    if (size != -1) {
      return size;
    }

    size = 0;
    for (int i = 0; i < this.spans_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, this.spans_.get(i));
    }
    size += this.unknownFields.getSerializedSize();
    this.memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof DumpSpans)) {
      return super.equals(obj);
    }
    final DumpSpans other = (DumpSpans) obj;

    if (!this.getSpansList().equals(other.getSpansList())) {
      return false;
    }
    if (!this.unknownFields.equals(other.unknownFields)) {
      return false;
    }
    return true;
  }

  @SuppressWarnings("unchecked")
  @Override
  public int hashCode() {
    if (this.memoizedHashCode != 0) {
      return this.memoizedHashCode;
    }
    int hash = 41;
    hash = 19 * hash + getDescriptor().hashCode();
    if (this.getSpansCount() > 0) {
      hash = 37 * hash + SPANS_FIELD_NUMBER;
      hash = 53 * hash + this.getSpansList().hashCode();
    }
    hash = 29 * hash + this.unknownFields.hashCode();
    this.memoizedHashCode = hash;
    return hash;
  }

  public static DumpSpans parseFrom(final java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static DumpSpans parseFrom(final java.nio.ByteBuffer data,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static DumpSpans parseFrom(final com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static DumpSpans parseFrom(final com.google.protobuf.ByteString data,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static DumpSpans parseFrom(final byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static DumpSpans parseFrom(final byte[] data,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static DumpSpans parseFrom(final java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static DumpSpans parseFrom(final java.io.InputStream input,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
        extensionRegistry);
  }

  public static DumpSpans parseDelimitedFrom(final java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static DumpSpans parseDelimitedFrom(final java.io.InputStream input,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
        extensionRegistry);
  }

  public static DumpSpans parseFrom(final com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static DumpSpans parseFrom(final com.google.protobuf.CodedInputStream input,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
        extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(final DumpSpans prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(final BuilderParent parent) {
    final Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * <pre>
   * Used to dump spans for later store&amp;process
   * </pre>
   *
   * Protobuf type {@code opencensus.proto.dump.v1.DumpSpans}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:opencensus.proto.dump.v1.DumpSpans)
      DumpSpansOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return DumpProto.internal_static_opencensus_proto_dump_v1_DumpSpans_descriptor;
    }

    @Override
    protected FieldAccessorTable internalGetFieldAccessorTable() {
      return DumpProto.internal_static_opencensus_proto_dump_v1_DumpSpans_fieldAccessorTable
          .ensureFieldAccessorsInitialized(DumpSpans.class, Builder.class);
    }

    // Construct using io.opencensus.proto.dump.DumpSpans.newBuilder()
    private Builder() {
      this.maybeForceBuilderInitialization();
    }

    private Builder(final BuilderParent parent) {
      super(parent);
      this.maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
        this.getSpansFieldBuilder();
      }
    }

    @Override
    public Builder clear() {
      super.clear();
      if (this.spansBuilder_ == null) {
        this.spans_ = java.util.Collections.emptyList();
        this.bitField0_ = this.bitField0_ & ~0x00000001;
      } else {
        this.spansBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return DumpProto.internal_static_opencensus_proto_dump_v1_DumpSpans_descriptor;
    }

    @Override
    public DumpSpans getDefaultInstanceForType() {
      return DumpSpans.getDefaultInstance();
    }

    @Override
    public DumpSpans build() {
      final DumpSpans result = this.buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public DumpSpans buildPartial() {
      final DumpSpans result = new DumpSpans(this);
      @SuppressWarnings("unused")
      final int from_bitField0_ = this.bitField0_;
      if (this.spansBuilder_ == null) {
        if ((this.bitField0_ & 0x00000001) != 0) {
          this.spans_ = java.util.Collections.unmodifiableList(this.spans_);
          this.bitField0_ = this.bitField0_ & ~0x00000001;
        }
        result.spans_ = this.spans_;
      } else {
        result.spans_ = this.spansBuilder_.build();
      }
      this.onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }

    @Override
    public Builder setField(final com.google.protobuf.Descriptors.FieldDescriptor field,
        final Object value) {
      return super.setField(field, value);
    }

    @Override
    public Builder clearField(final com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @Override
    public Builder clearOneof(final com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @Override
    public Builder setRepeatedField(final com.google.protobuf.Descriptors.FieldDescriptor field,
        final int index, final Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @Override
    public Builder addRepeatedField(final com.google.protobuf.Descriptors.FieldDescriptor field,
        final Object value) {
      return super.addRepeatedField(field, value);
    }

    @Override
    public Builder mergeFrom(final com.google.protobuf.Message other) {
      if (other instanceof DumpSpans) {
        return this.mergeFrom((DumpSpans) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(final DumpSpans other) {
      if (other == DumpSpans.getDefaultInstance()) {
        return this;
      }
      if (this.spansBuilder_ == null) {
        if (!other.spans_.isEmpty()) {
          if (this.spans_.isEmpty()) {
            this.spans_ = other.spans_;
            this.bitField0_ = this.bitField0_ & ~0x00000001;
          } else {
            this.ensureSpansIsMutable();
            this.spans_.addAll(other.spans_);
          }
          this.onChanged();
        }
      } else {
        if (!other.spans_.isEmpty()) {
          if (this.spansBuilder_.isEmpty()) {
            this.spansBuilder_.dispose();
            this.spansBuilder_ = null;
            this.spans_ = other.spans_;
            this.bitField0_ = this.bitField0_ & ~0x00000001;
            this.spansBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
                ? this.getSpansFieldBuilder()
                : null;
          } else {
            this.spansBuilder_.addAllMessages(other.spans_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      this.onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(final com.google.protobuf.CodedInputStream input,
        final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      DumpSpans parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (final com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (DumpSpans) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          this.mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int bitField0_;

    private java.util.List<io.opencensus.proto.trace.v1.Span> spans_ =
        java.util.Collections.emptyList();

    private void ensureSpansIsMutable() {
      if (!((this.bitField0_ & 0x00000001) != 0)) {
        this.spans_ = new java.util.ArrayList<>(this.spans_);
        this.bitField0_ |= 0x00000001;
      }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<io.opencensus.proto.trace.v1.Span, io.opencensus.proto.trace.v1.Span.Builder, io.opencensus.proto.trace.v1.SpanOrBuilder> spansBuilder_;

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    @Override
    public java.util.List<io.opencensus.proto.trace.v1.Span> getSpansList() {
      if (this.spansBuilder_ == null) {
        return java.util.Collections.unmodifiableList(this.spans_);
      } else {
        return this.spansBuilder_.getMessageList();
      }
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    @Override
    public int getSpansCount() {
      if (this.spansBuilder_ == null) {
        return this.spans_.size();
      } else {
        return this.spansBuilder_.getCount();
      }
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    @Override
    public io.opencensus.proto.trace.v1.Span getSpans(final int index) {
      if (this.spansBuilder_ == null) {
        return this.spans_.get(index);
      } else {
        return this.spansBuilder_.getMessage(index);
      }
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public Builder setSpans(final int index, final io.opencensus.proto.trace.v1.Span value) {
      if (this.spansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        this.ensureSpansIsMutable();
        this.spans_.set(index, value);
        this.onChanged();
      } else {
        this.spansBuilder_.setMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public Builder setSpans(final int index,
        final io.opencensus.proto.trace.v1.Span.Builder builderForValue) {
      if (this.spansBuilder_ == null) {
        this.ensureSpansIsMutable();
        this.spans_.set(index, builderForValue.build());
        this.onChanged();
      } else {
        this.spansBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public Builder addSpans(final io.opencensus.proto.trace.v1.Span value) {
      if (this.spansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        this.ensureSpansIsMutable();
        this.spans_.add(value);
        this.onChanged();
      } else {
        this.spansBuilder_.addMessage(value);
      }
      return this;
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public Builder addSpans(final int index, final io.opencensus.proto.trace.v1.Span value) {
      if (this.spansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        this.ensureSpansIsMutable();
        this.spans_.add(index, value);
        this.onChanged();
      } else {
        this.spansBuilder_.addMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public Builder addSpans(final io.opencensus.proto.trace.v1.Span.Builder builderForValue) {
      if (this.spansBuilder_ == null) {
        this.ensureSpansIsMutable();
        this.spans_.add(builderForValue.build());
        this.onChanged();
      } else {
        this.spansBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public Builder addSpans(final int index,
        final io.opencensus.proto.trace.v1.Span.Builder builderForValue) {
      if (this.spansBuilder_ == null) {
        this.ensureSpansIsMutable();
        this.spans_.add(index, builderForValue.build());
        this.onChanged();
      } else {
        this.spansBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public Builder addAllSpans(final Iterable<? extends io.opencensus.proto.trace.v1.Span> values) {
      if (this.spansBuilder_ == null) {
        this.ensureSpansIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(values, this.spans_);
        this.onChanged();
      } else {
        this.spansBuilder_.addAllMessages(values);
      }
      return this;
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public Builder clearSpans() {
      if (this.spansBuilder_ == null) {
        this.spans_ = java.util.Collections.emptyList();
        this.bitField0_ = this.bitField0_ & ~0x00000001;
        this.onChanged();
      } else {
        this.spansBuilder_.clear();
      }
      return this;
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public Builder removeSpans(final int index) {
      if (this.spansBuilder_ == null) {
        this.ensureSpansIsMutable();
        this.spans_.remove(index);
        this.onChanged();
      } else {
        this.spansBuilder_.remove(index);
      }
      return this;
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public io.opencensus.proto.trace.v1.Span.Builder getSpansBuilder(final int index) {
      return this.getSpansFieldBuilder().getBuilder(index);
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    @Override
    public io.opencensus.proto.trace.v1.SpanOrBuilder getSpansOrBuilder(final int index) {
      if (this.spansBuilder_ == null) {
        return this.spans_.get(index);
      } else {
        return this.spansBuilder_.getMessageOrBuilder(index);
      }
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    @Override
    public java.util.List<? extends io.opencensus.proto.trace.v1.SpanOrBuilder> getSpansOrBuilderList() {
      if (this.spansBuilder_ != null) {
        return this.spansBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(this.spans_);
      }
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public io.opencensus.proto.trace.v1.Span.Builder addSpansBuilder() {
      return this.getSpansFieldBuilder()
          .addBuilder(io.opencensus.proto.trace.v1.Span.getDefaultInstance());
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public io.opencensus.proto.trace.v1.Span.Builder addSpansBuilder(final int index) {
      return this.getSpansFieldBuilder().addBuilder(index,
          io.opencensus.proto.trace.v1.Span.getDefaultInstance());
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public java.util.List<io.opencensus.proto.trace.v1.Span.Builder> getSpansBuilderList() {
      return this.getSpansFieldBuilder().getBuilderList();
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<io.opencensus.proto.trace.v1.Span, io.opencensus.proto.trace.v1.Span.Builder, io.opencensus.proto.trace.v1.SpanOrBuilder> getSpansFieldBuilder() {
      if (this.spansBuilder_ == null) {
        this.spansBuilder_ =
            new com.google.protobuf.RepeatedFieldBuilderV3<>(
                this.spans_, (this.bitField0_ & 0x00000001) != 0, this.getParentForChildren(),
                this.isClean());
        this.spans_ = null;
      }
      return this.spansBuilder_;
    }

    @Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:opencensus.proto.dump.v1.DumpSpans)
  }

  // @@protoc_insertion_point(class_scope:opencensus.proto.dump.v1.DumpSpans)
  private static final DumpSpans DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new DumpSpans();
  }

  public static DumpSpans getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DumpSpans> PARSER =
      new com.google.protobuf.AbstractParser<>() {
        @Override
        public DumpSpans parsePartialFrom(final com.google.protobuf.CodedInputStream input,
            final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new DumpSpans(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<DumpSpans> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<DumpSpans> getParserForType() {
    return PARSER;
  }

  @Override
  public DumpSpans getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

