// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: dump/v1/dump.proto

package io.opencensus.proto.dump;

public final class DumpProto {
  private DumpProto() {}

  public static void registerAllExtensions(
      final com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(final com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor internal_static_opencensus_proto_dump_v1_DumpSpans_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_opencensus_proto_dump_v1_DumpSpans_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
  static {
    final String[] descriptorData = {"\n\022dump/v1/dump.proto\022\030opencensus.proto.d"
        + "ump.v1\032%opencensus/proto/trace/v1/trace."
        + "proto\";\n\tDumpSpans\022.\n\005spans\030\001 \003(\0132\037.open"
        + "census.proto.trace.v1.SpanBe\n\030io.opencen"
        + "sus.proto.dumpB\tDumpProtoP\001Z<github.com/"
        + "yancl/opencensus-go-exporter-kafka/gen-g" + "o/dump/v1b\006proto3"};
    final com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
          @Override
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              final com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
            io.opencensus.proto.trace.v1.TraceProto.getDescriptor(),},
        assigner);
    internal_static_opencensus_proto_dump_v1_DumpSpans_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_opencensus_proto_dump_v1_DumpSpans_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_opencensus_proto_dump_v1_DumpSpans_descriptor, new String[] {"Spans",});
    io.opencensus.proto.trace.v1.TraceProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
