// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: dump/v1/dump.proto

package io.opencensus.proto.dump;

/**
 * <pre>
 * Used to dump spans for later store&amp;process
 * </pre>
 *
 * Protobuf type {@code opencensus.proto.dump.v1.DumpSpans}
 */
public final class DumpSpans extends com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:opencensus.proto.dump.v1.DumpSpans)
    DumpSpansOrBuilder {
  private static final long serialVersionUID = 0L;

  // Use DumpSpans.newBuilder() to construct.
  private DumpSpans(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private DumpSpans() {
    spans_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private DumpSpans(com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              spans_ = new java.util.ArrayList<io.opencensus.proto.trace.v1.Span>();
              mutable_bitField0_ |= 0x00000001;
            }
            spans_.add(
                input.readMessage(io.opencensus.proto.trace.v1.Span.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        spans_ = java.util.Collections.unmodifiableList(spans_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return DumpProto.internal_static_opencensus_proto_dump_v1_DumpSpans_descriptor;
  }

  @Override
  protected FieldAccessorTable internalGetFieldAccessorTable() {
    return DumpProto.internal_static_opencensus_proto_dump_v1_DumpSpans_fieldAccessorTable
        .ensureFieldAccessorsInitialized(DumpSpans.class, Builder.class);
  }

  public static final int SPANS_FIELD_NUMBER = 1;
  private java.util.List<io.opencensus.proto.trace.v1.Span> spans_;

  /**
   * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
   */
  public java.util.List<io.opencensus.proto.trace.v1.Span> getSpansList() {
    return spans_;
  }

  /**
   * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
   */
  public java.util.List<? extends io.opencensus.proto.trace.v1.SpanOrBuilder> getSpansOrBuilderList() {
    return spans_;
  }

  /**
   * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
   */
  public int getSpansCount() {
    return spans_.size();
  }

  /**
   * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
   */
  public io.opencensus.proto.trace.v1.Span getSpans(int index) {
    return spans_.get(index);
  }

  /**
   * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
   */
  public io.opencensus.proto.trace.v1.SpanOrBuilder getSpansOrBuilder(int index) {
    return spans_.get(index);
  }

  private byte memoizedIsInitialized = -1;

  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1)
      return true;
    if (isInitialized == 0)
      return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    for (int i = 0; i < spans_.size(); i++) {
      output.writeMessage(1, spans_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1)
      return size;

    size = 0;
    for (int i = 0; i < spans_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, spans_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof DumpSpans)) {
      return super.equals(obj);
    }
    DumpSpans other = (DumpSpans) obj;

    if (!getSpansList().equals(other.getSpansList()))
      return false;
    if (!unknownFields.equals(other.unknownFields))
      return false;
    return true;
  }

  @SuppressWarnings("unchecked")
  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSpansCount() > 0) {
      hash = (37 * hash) + SPANS_FIELD_NUMBER;
      hash = (53 * hash) + getSpansList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static DumpSpans parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static DumpSpans parseFrom(java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static DumpSpans parseFrom(com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static DumpSpans parseFrom(com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static DumpSpans parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static DumpSpans parseFrom(byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static DumpSpans parseFrom(java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static DumpSpans parseFrom(java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
        extensionRegistry);
  }

  public static DumpSpans parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static DumpSpans parseDelimitedFrom(java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
        extensionRegistry);
  }

  public static DumpSpans parseFrom(com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static DumpSpans parseFrom(com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
        extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(DumpSpans prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * <pre>
   * Used to dump spans for later store&amp;process
   * </pre>
   *
   * Protobuf type {@code opencensus.proto.dump.v1.DumpSpans}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:opencensus.proto.dump.v1.DumpSpans)
      DumpSpansOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return DumpProto.internal_static_opencensus_proto_dump_v1_DumpSpans_descriptor;
    }

    @Override
    protected FieldAccessorTable internalGetFieldAccessorTable() {
      return DumpProto.internal_static_opencensus_proto_dump_v1_DumpSpans_fieldAccessorTable
          .ensureFieldAccessorsInitialized(DumpSpans.class, Builder.class);
    }

    // Construct using io.opencensus.proto.dump.DumpSpans.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
        getSpansFieldBuilder();
      }
    }

    @Override
    public Builder clear() {
      super.clear();
      if (spansBuilder_ == null) {
        spans_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        spansBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return DumpProto.internal_static_opencensus_proto_dump_v1_DumpSpans_descriptor;
    }

    @Override
    public DumpSpans getDefaultInstanceForType() {
      return DumpSpans.getDefaultInstance();
    }

    @Override
    public DumpSpans build() {
      DumpSpans result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public DumpSpans buildPartial() {
      DumpSpans result = new DumpSpans(this);
      @SuppressWarnings("unused")
      int from_bitField0_ = bitField0_;
      if (spansBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          spans_ = java.util.Collections.unmodifiableList(spans_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.spans_ = spans_;
      } else {
        result.spans_ = spansBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }

    @Override
    public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return super.setField(field, value);
    }

    @Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @Override
    public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @Override
    public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof DumpSpans) {
        return mergeFrom((DumpSpans) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(DumpSpans other) {
      if (other == DumpSpans.getDefaultInstance())
        return this;
      if (spansBuilder_ == null) {
        if (!other.spans_.isEmpty()) {
          if (spans_.isEmpty()) {
            spans_ = other.spans_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSpansIsMutable();
            spans_.addAll(other.spans_);
          }
          onChanged();
        }
      } else {
        if (!other.spans_.isEmpty()) {
          if (spansBuilder_.isEmpty()) {
            spansBuilder_.dispose();
            spansBuilder_ = null;
            spans_ = other.spans_;
            bitField0_ = (bitField0_ & ~0x00000001);
            spansBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
                ? getSpansFieldBuilder()
                : null;
          } else {
            spansBuilder_.addAllMessages(other.spans_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      DumpSpans parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (DumpSpans) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int bitField0_;

    private java.util.List<io.opencensus.proto.trace.v1.Span> spans_ =
        java.util.Collections.emptyList();

    private void ensureSpansIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        spans_ = new java.util.ArrayList<io.opencensus.proto.trace.v1.Span>(spans_);
        bitField0_ |= 0x00000001;
      }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<io.opencensus.proto.trace.v1.Span, io.opencensus.proto.trace.v1.Span.Builder, io.opencensus.proto.trace.v1.SpanOrBuilder> spansBuilder_;

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public java.util.List<io.opencensus.proto.trace.v1.Span> getSpansList() {
      if (spansBuilder_ == null) {
        return java.util.Collections.unmodifiableList(spans_);
      } else {
        return spansBuilder_.getMessageList();
      }
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public int getSpansCount() {
      if (spansBuilder_ == null) {
        return spans_.size();
      } else {
        return spansBuilder_.getCount();
      }
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public io.opencensus.proto.trace.v1.Span getSpans(int index) {
      if (spansBuilder_ == null) {
        return spans_.get(index);
      } else {
        return spansBuilder_.getMessage(index);
      }
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public Builder setSpans(int index, io.opencensus.proto.trace.v1.Span value) {
      if (spansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpansIsMutable();
        spans_.set(index, value);
        onChanged();
      } else {
        spansBuilder_.setMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public Builder setSpans(int index, io.opencensus.proto.trace.v1.Span.Builder builderForValue) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.set(index, builderForValue.build());
        onChanged();
      } else {
        spansBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public Builder addSpans(io.opencensus.proto.trace.v1.Span value) {
      if (spansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpansIsMutable();
        spans_.add(value);
        onChanged();
      } else {
        spansBuilder_.addMessage(value);
      }
      return this;
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public Builder addSpans(int index, io.opencensus.proto.trace.v1.Span value) {
      if (spansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpansIsMutable();
        spans_.add(index, value);
        onChanged();
      } else {
        spansBuilder_.addMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public Builder addSpans(io.opencensus.proto.trace.v1.Span.Builder builderForValue) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.add(builderForValue.build());
        onChanged();
      } else {
        spansBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public Builder addSpans(int index, io.opencensus.proto.trace.v1.Span.Builder builderForValue) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.add(index, builderForValue.build());
        onChanged();
      } else {
        spansBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public Builder addAllSpans(Iterable<? extends io.opencensus.proto.trace.v1.Span> values) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(values, spans_);
        onChanged();
      } else {
        spansBuilder_.addAllMessages(values);
      }
      return this;
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public Builder clearSpans() {
      if (spansBuilder_ == null) {
        spans_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        spansBuilder_.clear();
      }
      return this;
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public Builder removeSpans(int index) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.remove(index);
        onChanged();
      } else {
        spansBuilder_.remove(index);
      }
      return this;
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public io.opencensus.proto.trace.v1.Span.Builder getSpansBuilder(int index) {
      return getSpansFieldBuilder().getBuilder(index);
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public io.opencensus.proto.trace.v1.SpanOrBuilder getSpansOrBuilder(int index) {
      if (spansBuilder_ == null) {
        return spans_.get(index);
      } else {
        return spansBuilder_.getMessageOrBuilder(index);
      }
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public java.util.List<? extends io.opencensus.proto.trace.v1.SpanOrBuilder> getSpansOrBuilderList() {
      if (spansBuilder_ != null) {
        return spansBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(spans_);
      }
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public io.opencensus.proto.trace.v1.Span.Builder addSpansBuilder() {
      return getSpansFieldBuilder()
          .addBuilder(io.opencensus.proto.trace.v1.Span.getDefaultInstance());
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public io.opencensus.proto.trace.v1.Span.Builder addSpansBuilder(int index) {
      return getSpansFieldBuilder().addBuilder(index,
          io.opencensus.proto.trace.v1.Span.getDefaultInstance());
    }

    /**
     * <code>repeated .opencensus.proto.trace.v1.Span spans = 1;</code>
     */
    public java.util.List<io.opencensus.proto.trace.v1.Span.Builder> getSpansBuilderList() {
      return getSpansFieldBuilder().getBuilderList();
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<io.opencensus.proto.trace.v1.Span, io.opencensus.proto.trace.v1.Span.Builder, io.opencensus.proto.trace.v1.SpanOrBuilder> getSpansFieldBuilder() {
      if (spansBuilder_ == null) {
        spansBuilder_ =
            new com.google.protobuf.RepeatedFieldBuilderV3<io.opencensus.proto.trace.v1.Span, io.opencensus.proto.trace.v1.Span.Builder, io.opencensus.proto.trace.v1.SpanOrBuilder>(
                spans_, ((bitField0_ & 0x00000001) != 0), getParentForChildren(), isClean());
        spans_ = null;
      }
      return spansBuilder_;
    }

    @Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:opencensus.proto.dump.v1.DumpSpans)
  }

  // @@protoc_insertion_point(class_scope:opencensus.proto.dump.v1.DumpSpans)
  private static final DumpSpans DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new DumpSpans();
  }

  public static DumpSpans getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DumpSpans> PARSER =
      new com.google.protobuf.AbstractParser<DumpSpans>() {
        @Override
        public DumpSpans parsePartialFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new DumpSpans(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<DumpSpans> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<DumpSpans> getParserForType() {
    return PARSER;
  }

  @Override
  public DumpSpans getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

