name: Release Tagged Docker Image

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  release-docker-image-jvm:
    name: Release Tagged Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build and Push Image
        uses: explorviz/deployment/.github/actions/build-and-deploy-quarkus-jvm@main
        with:
          platforms: "linux/amd64,linux/arm64/v8"
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          image-name: ${{ vars.DOCKER_JVM_IMAGE_NAME }}
          image-tag: "${{ github.ref_name }}"
